from models.Move import Move
from models.enum.MoveCategory import MoveCategory
from models.pokemonType.utils.PokemonTypeEnum import PokemonType
from models.status.StatusEnum import StatusEnum


class MoveFactory:
    """
    Factory for creation of move (special factory more like a dict not really perfect implementation of the design pattern but adapted to our use case
    """

    __moves_dict = {
        "Éclair": Move(
            "Éclair",
            "Une attaque électrique puissante",
            85,
            100,
            PokemonType.ELECTRIC,
            MoveCategory.SPECIAL,
        ),
        "Flammèche": Move(
            "Flammèche",
            "Une attaque de feu",
            90,
            100,
            PokemonType.FIRE,
            MoveCategory.SPECIAL,
        ),
        "Séisme": Move(
            "Séisme",
            "Une attaque puissante de type sol ",
            100,
            100,
            PokemonType.GROUND,
            MoveCategory.PHYSICAL,
        ),
        "Surf": Move(
            "Surf",
            "Une attaque puissante de type eau",
            90,
            100,
            PokemonType.WATER,
            MoveCategory.SPECIAL,
        ),
        "Hydrocanon": Move(
            "Hydrocanon",
            "Une attaque très puissante de type eau.",
            110,
            80,
            PokemonType.WATER,
            MoveCategory.SPECIAL,
        ),
        "Laser Glace": Move(
            "Laser Glace",
            "Un rayon glacé",
            90,
            100,
            PokemonType.ICE,
            MoveCategory.SPECIAL,
        ),
        "Ball'Ombre": Move(
            "Ball'Ombre",
            "Une attaque de type spectre",
            80,
            100,
            PokemonType.GHOST,
            MoveCategory.SPECIAL,
        ),
        "Tonnerre": Move(
            "Tonnerre",
            "Une attaque électrique puissante",
            110,
            70,
            PokemonType.ELECTRIC,
            MoveCategory.SPECIAL,
        ),
        "Griffe Dragon": Move(
            "Griffe Dragon",
            "Une attaque physique de type dragon puissante.",
            80,
            100,
            PokemonType.DRAGON,
            MoveCategory.PHYSICAL,
        ),
        "Psychique": Move(
            "Psychique",
            "Une attaque psychique",
            90,
            100,
            PokemonType.PSYCHIC,
            MoveCategory.SPECIAL,
        ),
        "Bomb Beurk": Move(
            "Bomb Beurk",
            "Une attaque de poison",
            90,
            100,
            PokemonType.POISON,
            MoveCategory.SPECIAL,
        ),
        "Toxik": Move(
            "Toxik",
            "Une attaque empoisonnant gravement la cible.",
            0,
            90,
            PokemonType.POISON,
            MoveCategory.STATUS,
            StatusEnum.POISON
        ),
        "Paralysie": Move(
            "Paralysie",
            "Une attaque qui paralyse la cible.",
            0,
            90,
            PokemonType.ELECTRIC,
            MoveCategory.STATUS,
            StatusEnum.PARALYSIS
        ),
        "Mèche Enflammée": Move(
            "Mèche Enflammée",
            "Une attaque qui brûle la cible.",
            0,
            75,
            PokemonType.FIRE,
            MoveCategory.STATUS,
            StatusEnum.BURN
        ),
        "Tacle": Move(
            "Tacle",
            "Une attaque physique basique.",
            40,
            100,
            PokemonType.NORMAL,
            MoveCategory.PHYSICAL,
        ),
        "Psyko": Move(
            "Psyko",
            "Une attaque psychique",
            65,
            100,
            PokemonType.PSYCHIC,
            MoveCategory.SPECIAL,
        ),
        "Coup de Roc": Move(
            "Coup de Roc",
            "Une attaque physique de type roche qui peut provoquer un coup de maître.",
            75,
            90,
            PokemonType.ROCK,
            MoveCategory.PHYSICAL,
        ),
        "Queue de Fer": Move(
            "Queue de Fer",
            "Une attaque physique de type acier",
            100,
            75,
            PokemonType.STEEL,
            MoveCategory.PHYSICAL,
        ),
        "Tranch'Herbe": Move(
            "Tranch'Herbe",
            "Une attaque de type plante",
            90,
            100,
            PokemonType.GRASS,
            MoveCategory.PHYSICAL,
        ),
        "Tranche Nuit": Move(
            "Tranche Nuit",
            "Une attaque de type sombre",
            70,
            100,
            PokemonType.DARK,
            MoveCategory.PHYSICAL,
        ),
        "Puissance Terrestre": Move(
            "Puissance Terrestre",
            "Une attaque de type sol",
            90,
            100,
            PokemonType.GROUND,
            MoveCategory.SPECIAL,
        ),
        "Mâchouille": Move(
            "Mâchouille",
            "Une attaque de type sombre ",
            80,
            100,
            PokemonType.DARK,
            MoveCategory.PHYSICAL,
        ),
        "Bombe Graine": Move(
            "Bombe Graine",
            "Une attaque de type plante",
            80,
            100,
            PokemonType.GRASS,
            MoveCategory.PHYSICAL,
        ),
        "Poing Glacé": Move(
            "Poing Glacé",
            "Une attaque physique de type glace",
            75,
            100,
            PokemonType.ICE,
            MoveCategory.PHYSICAL,
        ),
        "Lance-Flamme": Move(
            "Lance-Flamme",
            "Une attaque de feu très puissante ",
            110,
            75,
            PokemonType.FIRE,
            MoveCategory.SPECIAL,
        ),
        "Requiem Sombre": Move(
            "Requiem Sombre",
            "Une attaque spectre rapide.",
            40,
            100,
            PokemonType.GHOST,
            MoveCategory.PHYSICAL,
        ),
        "Rafale Piquante": Move(
            "Rafale Piquante",
            "Une attaque de type vol rapide qui frappe fort.",
            70,
            100,
            PokemonType.FLYING,
            MoveCategory.PHYSICAL,
        ),
        "Tornade": Move(
            "Tornade",
            "Une attaque de type vol",
            40,
            100,
            PokemonType.FLYING,
            MoveCategory.PHYSICAL,
        ),
        "Poing Feu": Move(
            "Poing Feu",
            "Une attaque de type feu",
            80,
            100,
            PokemonType.FIRE,
            MoveCategory.PHYSICAL,
        ),
        "Poing Glace": Move(
            "Poing Glace",
            "Une attaque de type glace",
            90,
            100,
            PokemonType.ICE,
            MoveCategory.PHYSICAL,
        ),
        "Coup de Pied": Move(
            "Coup de Pied",
            "Une attaque physique de type combat",
            70,
            100,
            PokemonType.FIGHT,
            MoveCategory.PHYSICAL,
        ),
        "Poing de Fer": Move(
            "Poing de Fer",
            "Une attaque physique de type acier",
            60,
            100,
            PokemonType.STEEL,
            MoveCategory.PHYSICAL,
        ),
        "Coup de Boule": Move(
            "Coup de Boule",
            "Une attaque de type norma",
            50,
            100,
            PokemonType.NORMAL,
            MoveCategory.PHYSICAL,
        ),
        "Masse Poing": Move(
            "Masse Poing",
            "Une attaque de type combat.",
            60,
            100,
            PokemonType.FIGHT,
            MoveCategory.PHYSICAL,
        ),
        "Poing Mortel": Move(
            "Poing Mortel",
            "Une attaque qui empoisonne la cible.",
            0,
            100,
            PokemonType.POISON,
            MoveCategory.STATUS,
            StatusEnum.POISON
        ),
        "Hypnose": Move(
            "Hypnose",
            "Une attaque qui endort la cible avec une forte chance.",
            0,
            60,
            PokemonType.PSYCHIC,
            MoveCategory.STATUS,
            StatusEnum.SLEEP
        ),
        "Gel": Move(
            "Gel",
            "Une attaque qui gel l'ennemie",
            0,
            100,
            PokemonType.ICE,
            MoveCategory.STATUS,
            StatusEnum.FREEZE
        ),
        "Morsure": Move(
            "Morsure",
            "Une attaque de type ténèbres",
            60,
            100,
            PokemonType.DARK,
            MoveCategory.PHYSICAL,
        ),
        "Griffe": Move(
            "Griffe",
            "Une attaque de type normal",
            40,
            100,
            PokemonType.NORMAL,
            MoveCategory.PHYSICAL,
        ),
    }

    @staticmethod
    def get_move(name: str):
        """
        Return the move if name matched else None and print
        """
        if name not in MoveFactory.__moves_dict:
            print(f"Move {name} not found in the factory")
        return MoveFactory.__moves_dict.get(name, None)
